### PR TITLE
Optional Compass/Sass support

### PR DESCRIPTION
**Pull request by yivi**
I prefer Sass to Less, and use compass to preprocess everything and minify it; so I modified the Gruntfile so it can do so with minimal effort.

The defaul is still less, you just need a change in settings to choose one or the other (Althourh I reckon that once you chose one path or another, you'll just remove the other css preprocessor).

Also added a parameter in the git clone command in "build-plugin", so it brings as little history as possible before rm-fing ".git".

Regards!

### CODE REVIEW

**Comment by hlashbrooke** [comment]
Hi Ivan,

It's been a while, but if you're still keen to have this merged then please have a look at the conflicts that have cropped up since I merged some other PRs recently and let me know if you can work through them easily. The conflicts shouldn't be anything too intense to work out :)

**Comment by jonathanbossenger** [comment]
Hi @yivi I know it's been a while since this PR, but are you able to fix the conflicts, so that we can look into merging this in? Thanks

**Comment by grappler** [comment]
> Compass is no longer actively maintained.
https://github.com/Compass/compass

It would be better to have some type of grunt or gulp or even a simple node script for this.

**Comment by jonathanbossenger** [comment]
I have not heard from the original requester, so I am closing this PR

**Pull request closed without merging**
