### PR TITLE
Include possibility to customize options prefix

### PR DESCRIPTION
**Pull request by alantygel**
Wordpress uses a prefix to identify the options stored for each plugin. This PR creates the option of customizing this prefix in the build plugin bash script.

### CODE REVIEW

**Comment by jonathanbossenger** [comment]
@alantygel before this PR can be considered, could I ask you to please fix the conflicts.

Thanks

**Comment by jonathanbossenger** [comment]
@alantygel sorry to do this, first off thanks for the updated PR. 

However it seems that @e-baker's PR #89 makes some changes which yours will overwrite, you may need to rebase your develop branch with the latest develop branch from this repo to make sure you get the latest changes, and ensure your PR doesn't overwrite anything merged into develop this morning.

Thanks

**Comment by cornelRaiu** [comment]
@jonathanbossenger it seems that the merge commit overrode the changes in PR #89 . Can you please check that? Let me know if I should make another PR for the issue.

**Comment by jonathanbossenger** [comment]
@cornelRaiu sorry about that mate, please do create another PR and I'll get it merged in. Thanks

**Pull request merged**
