### PR TITLE
Travis CI and WPCS compliance

### PR DESCRIPTION
**Pull request by carl-alberto**
@jonathanbossenger Opening up a new PR because the last attempt is so far away from the current develop branch https://github.com/hlashbrooke/WordPress-Plugin-Template/pull/57 to keep everything clean.

There are still a few parts that need cleanup like some few parts that needs some nonce and input validations but I have put it temporarily under the ignore directives.

### CODE REVIEW

**Comment by jonathanbossenger** [comment]
Thanks @carl-alberto let me know once you think it's ready for review.

**Comment by carl-alberto** [comment]
@jonathanbossenger please do review them as per checking in my Travis check https://www.travis-ci.org/wpugph/WordPress-Plugin-Template, this should pass the latest WPCS  with at least 10 ignores which are not fatal but I think it is a good start, we can then clean or let others contribute to clean it up in the next weeks ahead but main point is 95% of the code is WPCS compliant without the ignores

**Comment by jonathanbossenger** [comment]
@carl-alberto sounds good, I'm happy with 95% vs 0%. Would you mind just resolving the conflict in includes/class-wordpress-plugin-template-settings.php, then I'll start the review. Thanks

**Comment by carl-alberto** [comment]
@jonathanbossenger done! :)

**Comment by jonathanbossenger** [comment]
Thanks, I'm merging this into `develop` and will manually review the changes next week, with a view to merge this into the `master` branch.

**Comment by carl-alberto** [comment]
Thanks, hopefully, all goes well, please feel free to ping me if there are any issues along the way 😄

**Pull request merged**
