### PR TITLE
WordPress Plugin Directory standards reviewed

### PR DESCRIPTION
**Pull request by rafasashi**
In some installations `plugin_basename` returns the full path of the plugin file resulting in missing the hook `plugin_action_links_{$plugin_file}`

I find it safer to use the hook `plugin_action_links` and compare the second argument `$file` with the value in `$this->parent->file`

### CODE REVIEW

**Comment by rafasashi** [comment]
Our last plugin submission to the WordPress directory triggered a couple of issues related to sanitizing and escaping values.

The last commit insure the Template compliance with WordPress coding standards.

Feel free to have a look and drop your observations here.

**Comment by jonathanbossenger** [comment]
Thanks for the PR @rafasashi, always nice to see the template improved. I'll do my best to review the changes in the coming week.

**Comment by rafasashi** [comment]
You are most welcome Jonathan. Thank you for supporting this boilerplate! As I mentioned to Hugh last time, it is an important part of the integrated workflow we provide to our users.

**Comment by jonathanbossenger** [comment]
So sorry @rafasashi March was an extensively busy month for me.

I have bumped this review up on my to-do list, and I will do my best to review it next week.

**Comment by Lenny4** [comment]
@jonathanbossenger any news on this ?

**Comment by jonathanbossenger** [comment]
I'm so sorry folks, I've just not had the time to review this. I will try and get it done in the coming weeks.

**Pull request closed without merging**
